name: Compilar SA-MP Pawn (FINAL REAL)

on:
  push:
    paths:
      - "gamemodes/*.pwn"
      - "filterscripts/*.pwn"
  pull_request:
    paths:
      - "gamemodes/*.pwn"
      - "filterscripts/*.pwn"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Baixar Pawn Compiler 3.10.10
      run: |
        wget https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz
        tar -xzf pawnc-3.10.10-linux.tar.gz
        chmod +x pawnc-3.10.10-linux/bin/pawncc

    - name: Criar pasta de compilados
      run: mkdir -p compiled

    - name: Compilar gamemodes
      run: |
        shopt -s nullglob
        for file in gamemodes/*.pwn; do
          name=$(basename "$file" .pwn)
          echo "Compilando gamemode: $file"
          ./pawnc-3.10.10-linux/bin/pawncc "$file" -i./include -ocompiled/$name.amx
        done

    - name: Compilar filterscripts
      run: |
        shopt -s nullglob
        for file in filterscripts/*.pwn; do
          name=$(basename "$file" .pwn)
          echo "Compilando filterscript: $file"
          ./pawnc-3.10.10-linux/bin/pawncc "$file" -i./include -ocompiled/$name.amx
        done

    - name: Upload dos AMX
      uses: actions/upload-artifact@v4
      with:
        name: amx-files
        path: compiled/*.amx
