name: Compilar SA-MP Pawn

on:
  push:
    paths:
      - "gamemodes/*.pwn"
  pull_request:
    paths:
      - "gamemodes/*.pwn"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Baixar e configurar Pawn Compiler
      run: |
        wget https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz
        tar -xzf pawnc-3.10.10-linux.tar.gz
        chmod +x pawnc-3.10.10-linux/bin/pawncc

        # Caminho do binário
        echo "$(pwd)/pawnc-3.10.10-linux/bin" >> $GITHUB_PATH

        # Caminho da lib (CORREÇÃO DO libpawnc.so)
        echo "LD_LIBRARY_PATH=$(pwd)/pawnc-3.10.10-linux/bin" >> $GITHUB_ENV

    - name: Compilar gamemodes
      run: |
        mkdir -p compiled
        for file in gamemodes/*.pwn; do
          echo "Compilando $file"
          pawncc "$file" -i./include -o "compiled/$(basename "${file%.pwn}.amx")"
        done

    - name: Upload dos AMX
      uses: actions/upload-artifact@v4
      with:
        name: gamemodes-amx
        path: compiled/*.amx
