name: Compilar SA-MP

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependÃªncias
        run: |
          sudo apt update
          sudo apt install -y wget tar

      - name: Baixar Pawn Compiler
        run: |
          wget https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz
          tar -xzf pawnc-3.10.10-linux.tar.gz

      - name: Registrar libpawnc.so
        run: |
          sudo cp pawnc-3.10.10-linux/lib/libpawnc.so /usr/lib/
          sudo ldconfig

            - name: Compilar gamemodes
        run: |
          mkdir -p compiled

          for file in gamemodes/*.pwn; do
            echo "Compilando $file"
            ./pawnc-3.10.10-linux/bin/pawncc "$file" -i./include -o "compiled/$(basename "${file%.pwn}.amx")"
          done


      - name: Upload AMX
        uses: actions/upload-artifact@v4
        with:
          name: gamemodes-amx
          path: compiled/*.amx
